FROM cypress/browsers:chrome67

ENV APP /usr/src/app
WORKDIR $APP

COPY package.json $APP/package.json
RUN (npm install --no-save puppeteer@1.10.0 && npm run cypress:install) > /dev/null

COPY cypress $APP/cypress
COPY cypress.json $APP/cypress.json

RUN ./node_modules/.bin/cypress verify
